name: CI VTK Streaming

on:
  pull_request:
    branches: [wheel]
  push:
    branches: [wheel]

jobs:
  build-test:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        py-abi: ["cp310"]
        include:
          # Python version to install on host
          - py-abi: cp310
            python-version: "3.10"
          # OS name to ciwheelbuild platform name
          - os: ubuntu-latest
            build-target: "manylinux_x86_64"
          - os: windows-latest
            build-target: "win_amd64"
          - os: macos-latest
            build-target: "macosx_arm64"
    uses: ./.github/workflows/build-wheels.yml
    with:
      os: ${{ matrix.os }}
      build-target: ${{ matrix.py-abi }}-${{ matrix.build-target }}
      python-version: ${{ matrix.python-version }}
